.PHONY: clean All

All:
	@echo "----------Building project:[ simulator - Debug ]----------"
	@"$(MAKE)" -f  "simulator.mk"
clean:
	@echo "----------Cleaning project:[ simulator - Debug ]----------"
	@"$(MAKE)" -f  "simulator.mk" clean
